### ISSUE TITLE
Crash when placing station module outside road

### ISSUE THREAD

**Issue by rodrigmatrix** [thx114/ModularSubwayStationAssetsPack#2]
Hey. I really love this mod but if I place a station by accident outside a road, I'll get a crash. Here's a video and logs

https://github.com/thx114/ModularSubwayStationAssetsPack/assets/7853887/b3d88340-fe08-44c8-a32d-7767bb175993

```
[object Object]
Colossal.Logging.CustomLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
cohtml.LogWriter:Log(Severity, String)
cohtml.LogHandler:WriteLog(Severity, String)
cohtml.LogHandler:WriteLog(Severity, String, UInt32)
cohtml.Net.ILogHandler:SwigDirectorWriteLog(Int32, String, UInt32)
cohtml.Net.cohtmlNativePINVOKE:ILogHandler_WriteLog(HandleRef, Int32, String, UInt32)
cohtml.Net.ILogHandler:WriteLog(Severity, String, UInt32)
cohtml.Net.Binder:LogException(Exception)
cohtml.Net.Invoker:ExecuteAndSendResult(Binder, Delegate, Object[], Boolean)
cohtml.Net.Invoker:Invoke(Int32)
cohtml.Net.cohtmlNativePINVOKE:View_Advance(HandleRef, UInt32, Double)
cohtml.Net.View:Advance(UInt32, Double)
Colossal.UI.UIView:Update()
Colossal.UI.UISystem:Update()
Colossal.UI.UIManager:Update()
Game.SceneFlow.GameManager:UpdateUI()
Game.SceneFlow.GameManager:Update()
```

**Comment by thx114** [comment]
Ensure that the mod order is placed after the prerequisite mods. Then, restart the game multiple times to ensure that assets are not loaded repeatedly.

**Comment by rodrigmatrix** [comment]
@thx114 no luck unfortunatly. After the new patch, when I save and focus on a modular station, the game crashes. This is the only asset that this is happening. I've already reset all assets, changed loading order, deleted all mods but no luck. Some of the logs:

[Player.log](https://github.com/thx114/ModularSubwayStationAssetsPack/files/15136852/Player.log)
```
=================================================================
Native Crash Reporting
=================================================================
Got a UNKNOWN while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================

=================================================================
Managed Stacktrace:
=================================================================
at <unknown> <0xffffffff>
at cohtml.Net.cohtmlNativePINVOKE:ResourceResponse_SetStatus <0x0009d>
at cohtml.Net.ResourceResponse:SetStatus <0x00052>
at <RequestAsync>d__37:MoveNext <0x00338>
at UnityEngine.SetupCoroutine:InvokeMoveNext <0x0004f>
at <Module>:runtime_invoke_void_object_intptr <0x0008e>
=================================================================
```

```
=================================================================
Native Crash Reporting
=================================================================
Got a UNKNOWN while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================

=================================================================
Managed Stacktrace:
=================================================================
at <unknown> <0xffffffff>
at cohtml.Net.cohtmlNativePINVOKE:ResourceResponse_Finish <0x0009d>
at cohtml.Net.ResourceResponse:Finish <0x00052>
at ResourceRequestData:RespondWithFailure <0x0003e>
at Colossal.UI.DefaultResourceHandler:CheckForFailedRequest <0x0004a>
at <RequestResourceAsync>d__33:MoveNext <0x0049a>
at UnityEngine.SetupCoroutine:InvokeMoveNext <0x0004f>
at <Module>:runtime_invoke_void_object_intptr <0x0008e>
```

**Comment by thx114** [comment]
This should have been fixed after the APM update.

**Comment by rodrigmatrix** [comment]
@thx114 unfortunately, it's still not working. The issue happens only to subway assets. I'm using a lot of assets and none of them have this issue
![Screenshot (10)](https://github.com/thx114/ModularSubwayStationAssetsPack/assets/7853887/17bab56e-3604-4703-aa18-45373d30710e)

```
=================================================================
	Native Crash Reporting
=================================================================
Got a UNKNOWN while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================

=================================================================
	Managed Stacktrace:
=================================================================
	  at <unknown> <0xffffffff>
	  at cohtml.Net.cohtmlNativePINVOKE:View_TriggerEvent <0x000bd>
	  at cohtml.Net.View:TriggerEvent <0x00052>
	  at ExtraUIScreens.EuisScreenManager:SendTriggerToView <0x00071>
	  at ExtraUIScreens.EuisScreenManager:SendEventToApp <0x0080a>
	  at <>c__DisplayClass54_1:<RegisterModActions>b__0 <0x00042>
	  at BelzontAdr.AdrMainSystem:NotifyChanges <0x0004d>
	  at BelzontAdr.AdrMainSystem:set_CurrentCitySettings <0x0003a>
	  at BelzontAdr.AdrMainSystem:Deserialize <0x001da>
	  at BelzontAdr.AdrMainSystem:Belzont.Serialization.IBelzontSerializableSingleton<BelzontAdr.AdrMainSystem>.Deserialize <0x00082>
	  at Belzont.Serialization.BelzontDeserializeJob`2:Execute <0x00168>
	  at JobStruct`1:Execute <0x0001a>
	  at ExecuteJobFunction:invoke_void_T&_intptr_intptr_JobRanges&_int <0x000b9>
	  at <Module>:runtime_invoke_void__this___intptr&_intptr_intptr_intptr&_int <0x000b5>
=================================================================
```

**Comment by rodrigmatrix** [comment]
Fixed with new asset manager version
